# Generated by Django 3.2.3 on 2021-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nus_module_code', models.CharField(max_length=10, unique=True)),
                ('nus_module_title', models.CharField(max_length=50)),
                ('nus_module_credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModulePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nus_module_code', models.CharField(max_length=10)),
                ('nus_module_title', models.CharField(max_length=50)),
                ('partner_module_code', models.CharField(max_length=10)),
                ('partner_module_credit', models.CharField(max_length=10)),
                ('partner_university', models.CharField(max_length=100)),
                ('partner_country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_university', models.CharField(max_length=100, unique=True)),
                ('partner_information', models.TextField()),
                ('partner_country', models.CharField(max_length=20)),
            ],
        ),
    ]
