# Generated by Django 3.2.3 on 2021-06-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepair',
            name='partner_module_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modulepair',
            name='partner_module_credit',
            field=models.CharField(max_length=100),
        ),
    ]
