# Generated by Django 3.2.2 on 2021-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210611_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='nus_module_faculty',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
    ]
