# Generated by Django 3.2.2 on 2021-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modulepair_partner_module_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepair',
            name='partner_module_title',
            field=models.CharField(max_length=100),
        ),
    ]
