# Generated by Django 3.2.2 on 2021-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_modulepair_partner_module_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='nus_module_description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
