# Generated by Django 3.2.2 on 2021-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_module_nus_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='nus_module_faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='nus_module_title',
            field=models.CharField(max_length=100),
        ),
    ]
