# Generated by Django 3.2.2 on 2021-06-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepair',
            name='nus_module_title',
            field=models.CharField(max_length=100),
        ),
    ]
