export const structuredFacultyContent = [
    {"facultyName" : "All"},
    {"facultyName" : "Faculty of Arts and Social Sciences"},
    {"facultyName" : "School of Computing"},
    {"facultyName" : "School of Cont and Lifelong Education"},
    {"facultyName" : "Faculty of Dentistry"},
    {"facultyName" : "School of Design and Environment"},
    {"facultyName" : "Yong Loo Lin Sch of Medicine"},
    {"facultyName" : "Faculty of Engineering"},
    {"facultyName" : "Institute of Systems Science"},
    {"facultyName" : "Faculty of Law"},
    {"facultyName" : "LKY School of Public Policy"},
    {"facultyName" : "Logistics Inst-Asia Pac"},
    {"facultyName" : "Multi Disciplinary Programme"},
    {"facultyName" : "NUS Business School"},
    {"facultyName" : "NUS Graduate Sch for Int Science & Engineering"},
    {"facultyName" : "Residential College"},
    {"facultyName" : "Risk Management Institute"},
    {"facultyName" : "Faculty of Science"},
    {"facultyName" : "SSH School of Public Health"},
    {"facultyName" : "Temasek Defence Sys. Institute"},
    {"facultyName" : "University Scholars Programme"},
    {"facultyName" : "Yale-NUS College"},
    {"facultyName" : "YST Conservatory of Music"},
    {"facultyName" : "Singapore-MIT Alliance"},
    {"facultyName" : "Mechanobiology Institute (MBI)"},
    {"facultyName" : "Duke-NUS Medical School"}
]
