export const structuredUniversityContent = [
    {"universityName": "Aarhus University"}, 
    {"universityName": "Albert-Ludwig University of Freiburg (University of Freiburg)"}, 
    {"universityName": "Arizona State University"}, 
    {"universityName": "Australian National University"}, 
    {"universityName": "Bilkent University"}, 
    {"universityName": "Boston College"}, 
    {"universityName": "Boston University"}, 
    {"universityName": "Brandeis University"}, 
    {"universityName": "Budapest University of Technology and Economics"}, 
    {"universityName": "Carleton College"}, 
    {"universityName": "Carnegie Mellon University"}, 
    {"universityName": "Case Western Reserve University"}, 
    {"universityName": "CentraleSup‚lec"}, 
    {"universityName": "Chalmers University of Technology"}, 
    {"universityName": "Chongqing University"}, 
    {"universityName": "Chulalongkorn University"}, 
    {"universityName": "City University of Hong Kong"}, 
    {"universityName": "Clarkson University"}, 
    {"universityName": "Communaut‚ Universit‚ Grenoble Alpes"}, 
    {"universityName": "Concordia University"}, 
    {"universityName": "Cornell University College of Agriculture & Life Sciences (CALS)"}, 
    {"universityName": "Cornell University College of Human Ecology"}, 
    {"universityName": "Cracow University of Technology"}, 
    {"universityName": "Dalhousie University"}, 
    {"universityName": "Delft University of Technology"}, 
    {"universityName": "Durham University"}, 
    {"universityName": "ETH Zurich (Swiss Federal Institute of Technology)"}, 
    {"universityName": "Ecole Nationale Sup‚rieure des Mines de Paris (MINES ParisTech)"}, 
    {"universityName": "Ecole Polytechnique F‚d‚rale de Lausanne (EPFL)"}, 
    {"universityName": "Eindhoven University of Technology"}, 
    {"universityName": "Emory University"}, 
    {"universityName": "Free University of Berlin"}, 
    {"universityName": "Fudan University"}, 
    {"universityName": "George Washington University"}, 
    {"universityName": "Georgetown University"}, 
    {"universityName": "Georgia Institute of Technology"}, 
    {"universityName": "Humboldt University of Berlin"}, 
    {"universityName": "Imperial College London"}, 
    {"universityName": "Institut National des Sciences Appliqu‚es de Lyon (INSA Lyon)"}, 
    {"universityName": "Interdisciplinary Center Herzliya"}, 
    {"universityName": "Jagiellonian University"}, 
    {"universityName": "KTH - Royal Institute of Technology"}, 
    {"universityName": "Karlsruhe Institute of Technology"}, 
    {"universityName": "Keio University"}, 
    {"universityName": "King's College London"}, 
    {"universityName": "Korea Advanced Institute of Science and Technology (KAIST)"}, 
    {"universityName": "Korea University"}, 
    {"universityName": "Kyoto University"}, 
    {"universityName": "Kyushu University"}, 
    {"universityName": "Ludwig-Maximilians-University of Munich"}, 
    {"universityName": "Lund University"}, 
    {"universityName": "Mahidol University"}, 
    {"universityName": "McGill University"}, 
    {"universityName": "Monash University"}, 
    {"universityName": "Nagoya University"}, 
    {"universityName": "Nanjing University"}, 
    {"universityName": "National Cheng Kung University"}, 
    {"universityName": "National Chiao Tung University"}, 
    {"universityName": "National Taiwan University"}, 
    {"universityName": "National Tsing Hua University"}, 
    {"universityName": "Newcastle University"}, 
    {"universityName": "Northwestern University"}, 
    {"universityName": "Norwegian University of Science & Technology"}, 
    {"universityName": "Osaka University"}, 
    {"universityName": "Peking University"}, 
    {"universityName": "Pennsylvania State University"}, 
    {"universityName": "Pohang University of Science and Technology"}, 
    {"universityName": "Purdue University"}, 
    {"universityName": "Queen's University, Kingston"}, 
    {"universityName": "RWTH Aachen University"}, 
    {"universityName": "Rheinische Friedrich-Wilhelms-Universit„t Bonn (University of Bonn)"}, 
    {"universityName": "Rice University"}, 
    {"universityName": "Ruprecht Charles University of Heidelberg (Heidelberg University)"}, 
    {"universityName": "Sabanci University"}, 
    {"universityName": "Sciences Po"}, 
    {"universityName": "Seoul National University"}, 
    {"universityName": "Shanghai Jiao Tong University"}, 
    {"universityName": "Simon Fraser University"}, 
    {"universityName": "Stockholm University"}, 
    {"universityName": "Sun Yat-Sen University"}, 
    {"universityName": "TELECOM ParisTech"}, 
    {"universityName": "Tallinn University of Technology"}, 
    {"universityName": "Technical University of Darmstadt"}, 
    {"universityName": "Technical University of Denmark"}, 
    {"universityName": "Technical University of Hamburg (Hamburg University of Technology)"}, 
    {"universityName": "Technical University of Munich"}, 
    {"universityName": "Technion-Israel Institute of Technology"}, 
    {"universityName": "Technologico de Monterrey"}, 
    {"universityName": "Texas A&M University"}, 
    {"universityName": "The Chinese University of Hong Kong"}, 
    {"universityName": "The College of William and Mary"}, 
    {"universityName": "The Hebrew University of Jerusalem"}, 
    {"universityName": "The Hong Kong Polytechnic University"}, 
    {"universityName": "The University of Bath"}, 
    {"universityName": "The University of Edinburgh"}, 
    {"universityName": "The University of Hong Kong"}, 
    {"universityName": "The University of Liverpool"}, 
    {"universityName": "The University of Manchester"}, 
    {"universityName": "The University of Nottingham"}, 
    {"universityName": "The University of Sheffield"}, 
    {"universityName": "The University of Tokyo"}, 
    {"universityName": "The University of Warwick"}, 
    {"universityName": "The University of York"}, 
    {"universityName": "Tohoku University"}, 
    {"universityName": "Tokyo Institute of Technology"}, 
    {"universityName": "Tongji University"}, 
    {"universityName": "Trinity College Dublin"}, 
    {"universityName": "Tsinghua University"}, 
    {"universityName": "Tulane University"}, 
    {"universityName": "Universidad Autonoma De Madrid"}, 
    {"universityName": "University College Cork"}, 
    {"universityName": "University College Dublin"}, 
    {"universityName": "University College London"}, 
    {"universityName": "University of Adelaide"}, 
    {"universityName": "University of Alaska Fairbanks"}, 
    {"universityName": "University of Alberta"}, 
    {"universityName": "University of Amsterdam (includes Amsterdam University College)"}, 
    {"universityName": "University of Antwerp"}, 
    {"universityName": "University of Arizona"}, 
    {"universityName": "University of Auckland"}, 
    {"universityName": "University of Birmingham"}, 
    {"universityName": "University of Bologna"}, 
    {"universityName": "University of Bristol"}, 
    {"universityName": "University of British Columbia"}, 
    {"universityName": "University of Calgary"}, 
    {"universityName": "University of California (System-Wide)"}, 
    {"universityName": "University of Canterbury"}, 
    {"universityName": "University of Colorado Boulder"}, 
    {"universityName": "University of Connecticut"}, 
    {"universityName": "University of Copenhagen"}, 
    {"universityName": "University of Florida"}, 
    {"universityName": "University of Geneva"}, 
    {"universityName": "University of Glasgow"}, 
    {"universityName": "University of Gothenburg"}, 
    {"universityName": "University of Guelph"}, 
    {"universityName": "University of Hawaii at Manoa"}, 
    {"universityName": "University of Helsinki"}, 
    {"universityName": "University of Hohenheim"}, 
    {"universityName": "University of Iceland"}, 
    {"universityName": "University of Illinois at Urbana-Champaign"}, 
    {"universityName": "University of Innsbruck"}, 
    {"universityName": "University of Konstanz"}, 
    {"universityName": "University of Lausanne"}, 
    {"universityName": "University of Leeds"}, 
    {"universityName": "University of Mannheim"}, 
    {"universityName": "University of Maryland"}, 
    {"universityName": "University of Melbourne"}, 
    {"universityName": "University of Miami"}, 
    {"universityName": "University of Michigan"}, 
    {"universityName": "University of New South Wales"}, 
    {"universityName": "University of North Carolina at Chapel Hill"}, 
    {"universityName": "University of Notre Dame"}, 
    {"universityName": "University of Oregon"}, 
    {"universityName": "University of Oslo"}, 
    {"universityName": "University of Otago"}, 
    {"universityName": "University of Ottawa"}, 
    {"universityName": "University of Pennsylvania"}, 
    {"universityName": "University of Pittsburgh"}, 
    {"universityName": "University of Pretoria"}, 
    {"universityName": "University of Queensland"}, 
    {"universityName": "University of Southern California"}, 
    {"universityName": "University of St Andrews"}, 
    {"universityName": "University of Stuttgart"}, 
    {"universityName": "University of Sydney"}, 
    {"universityName": "University of Texas at Austin"}, 
    {"universityName": "University of Toronto"}, 
    {"universityName": "University of Tubingen (Eberhard Karls University of Tübingen)"}, 
    {"universityName": "University of Ulm"}, 
    {"universityName": "University of Victoria"}, 
    {"universityName": "University of Virginia"}, 
    {"universityName": "University of Washington, Seattle"}, 
    {"universityName": "University of Waterloo"}, 
    {"universityName": "University of Western Australia"}, 
    {"universityName": "University of Western Ontario"}, 
    {"universityName": "University of Wisconsin - Madison"}, 
    {"universityName": "University of Zagreb"}, 
    {"universityName": "University of Zurich"}, 
    {"universityName": "Universit‚ de Technologie de CompiŠgne (UTC)"}, 
    {"universityName": "Universit‚ de Technologie de Troyes (UTT)"}, 
    {"universityName": "Uppsala University"}, 
    {"universityName": "Utrecht University (includes University College Utrecht and University Medical Center Utrecht)"}, 
    {"universityName": "Victoria University of Wellington"}, 
    {"universityName": "Vilnius University"}, 
    {"universityName": "Warsaw University of Technology"}, 
    {"universityName": "Waseda University"}, 
    {"universityName": "Xiamen University"}, 
    {"universityName": "Yonsei University"}, 
    {"universityName": "York University"}, 
    {"universityName": "Zhejiang University"}, 
]

